import { MacBook } from "assets";

export type Products = {
  id: string;
  picture: string;
  title: string;
  numClick: number;
  price: number;
  lowestPrice: number;
  vendorCount: number;
  vendorRank: number;
  lastUpdate: string;
  category: string;
  brand: string;
  inventory: number;
  viewNumber: number;
  status: "success" | "progress" | "failed";
  link: string;
  commercial: string;
  type: string;
  hasInsurance: boolean;
};

export const products: Products[] = [
  {
    id: "1",
    picture: MacBook,
    title: "Wireless Earbuds",
    numClick: 345,
    price: 12000000,
    lowestPrice: 200003232,
    vendorCount: 5,
    vendorRank: 1,
    lastUpdate: "2024-09-01",
    category: "Electronics",
    status: "failed",
    link: "/something",
    brand: "samsung",
    inventory: 120,
    viewNumber: 200,
    commercial: "آیتی بازار",
    type: "Accessory",
    hasInsurance: true,
  },
  {
    id: "2",
    picture: MacBook,
    title: "Smart Watch",
    numClick: 550,
    price: 12000000,
    lowestPrice: 200003232,
    vendorCount: 8,
    vendorRank: 2,
    lastUpdate: "2024-09-05",
    category: "Wearables",
    status: "progress",
    link: "/something",
    brand: "samsung",
    inventory: 120,
    viewNumber: 200,
    commercial: "آیتی بازار",
    type: "Accessory",
    hasInsurance: false,
  },
  {
    id: "3",
    picture: MacBook,
    title: "4K LED TV",
    numClick: 720,
    price: 12000000,
    lowestPrice: 200003232,
    vendorCount: 4,
    vendorRank: 1,
    lastUpdate: "2024-09-10",
    category: "Home Entertainment",
    status: "success",
    link: "/something",
    brand: "samsung",
    inventory: 120,
    viewNumber: 200,
    commercial: "آیتی بازار",
    type: "Accessory",
    hasInsurance: false,
  },
  {
    id: "4",
    picture: MacBook,
    title: "Gaming Laptop",
    numClick: 290,
    price: 12000000,
    lowestPrice: 200003232,
    vendorCount: 3,
    vendorRank: 1,
    lastUpdate: "2024-09-12",
    category: "Computers",
    status: "success",
    link: "/something",
    brand: "samsung",
    inventory: 120,
    viewNumber: 200,
    commercial: "آیتی بازار",
    type: "Accessory",
    hasInsurance: true,
  },
  {
    id: "5",
    picture: MacBook,
    title: "Noise Cancelling Headphones",
    numClick: 480,
    price: 12000000,
    lowestPrice: 200003232,
    vendorCount: 6,
    vendorRank: 2,
    lastUpdate: "2024-09-08",
    category: "Audio",
    status: "success",
    link: "/something",
    brand: "samsung",
    inventory: 120,
    viewNumber: 200,
    commercial: "آیتی بازار",
    type: "Accessory",
    hasInsurance: true,
  },
  {
    id: "6",
    picture: MacBook,
    title: "Smartphone",
    numClick: 850,
    price: 12000000,
    lowestPrice: 200003232,
    vendorCount: 10,
    vendorRank: 1,
    lastUpdate: "2024-09-15",
    status: "progress",
    link: "/something",
    brand: "samsung",
    inventory: 120,
    viewNumber: 200,
    commercial: "آیتی بازار",
    type: "Accessory",
    hasInsurance: false,
    category: "Mobile Phones",
  },
  {
    id: "7",
    picture: MacBook,
    title: "Bluetooth Speaker",
    numClick: 130,
    price: 12000000,
    lowestPrice: 200003232,
    vendorCount: 7,
    vendorRank: 3,
    lastUpdate: "2024-09-14",
    category: "Audio",
    status: "success",
    link: "/something",
    brand: "samsung",
    inventory: 120,
    viewNumber: 200,
    commercial: "آیتی بازار",
    type: "Accessory",
    hasInsurance: true,
  },
  {
    id: "8",
    picture: MacBook,
    title: "Home Security Camera",
    numClick: 250,
    price: 12000000,
    lowestPrice: 200003232,
    vendorCount: 4,
    vendorRank: 2,
    lastUpdate: "2024-09-13",
    category: "Smart Home",
    status: "progress",
    link: "/something",
    brand: "samsung",
    inventory: 120,
    viewNumber: 200,
    commercial: "آیتی بازار",
    type: "Accessory",
    hasInsurance: true,
  },
  {
    id: "9",
    picture: MacBook,
    title: "Electric Toothbrush",
    numClick: 150,
    price: 12000000,
    lowestPrice: 200003232,
    vendorCount: 5,
    vendorRank: 4,
    lastUpdate: "2024-09-16",
    category: "Health & Personal Care",
    status: "success",
    link: "/something",
    brand: "samsung",
    inventory: 120,
    viewNumber: 200,
    commercial: "آیتی بازار",
    type: "Accessory",
    hasInsurance: false,
  },
  {
    id: "10",
    picture: MacBook,
    title: "Air Purifier",
    numClick: 340,
    price: 12000000,
    lowestPrice: 200003232,
    vendorCount: 6,
    vendorRank: 2,
    lastUpdate: "2024-09-07",
    category: "Home Appliances",
    status: "failed",
    link: "/something",
    brand: "samsung",
    inventory: 120,
    viewNumber: 200,
    commercial: "آیتی بازار",
    type: "Accessory",
    hasInsurance: true,
  },
];
